### ISSUE TITLE
Facing issue when running the code

### ISSUE THREAD

**Issue by SaiSakethAluru** [SpiritSeeker/visualizer#3]
```
Traceback (most recent call last):
  File "/home/saketh/Eden/EdenPlayer/_EMusicPlayer.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('__EMusicPlayer', [dirname(__file__)])
  File "/home/saketh/anaconda3/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '__EMusicPlayer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eden_main.py", line 5, in <module>
    from EdenPlayer.EMusicPlayer import EMusicPlayer
  File "/home/saketh/Eden/EdenPlayer/EMusicPlayer.py", line 28, in <module>
    _EMusicPlayer = swig_import_helper()
  File "/home/saketh/Eden/EdenPlayer/EMusicPlayer.py", line 24, in swig_import_helper
    _mod = imp.load_module('_EMusicPlayer', fp, pathname, description)
  File "/home/saketh/anaconda3/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/home/saketh/anaconda3/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "/home/saketh/Eden/EdenPlayer/_EMusicPlayer.py", line 28, in <module>
    __EMusicPlayer = swig_import_helper()
  File "/home/saketh/Eden/EdenPlayer/_EMusicPlayer.py", line 20, in swig_import_helper
    import __EMusicPlayer
ModuleNotFoundError: No module named '__EMusicPlayer
```

**Comment by SpiritSeeker** [comment]
Go to EdenPlayer/ and hit `make`
